version: '3.7'

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  JWKS: ''
  MONGO_DB_PRO: mongodb://localhost:27017/addameapi

services:
  app:
    tty: true
    stdin_open: true
    image: addamespb/chat_engine
    build:
      context: .
    environment:
      <<: *shared_environment
    ports:
      - '6060:6060'
#    user: '0' # uncomment to run as root for testing purposes even though Dockerfile defines 'vapor' user.
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "6060"]

